name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: ./gradlew build

      - name: Move plugins
        run: mkdir -p out/plugins && mv -t out/plugins ./plugins/*/build/libs/*

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          path: |
            build/libs
            out/plugins